---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-bridge
  failurePolicy: Fail
  name: mbridge-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridges
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-bridgetemplate
  failurePolicy: Fail
  name: mbridgetemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridgetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-uplink
  failurePolicy: Fail
  name: muplink-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-uplinktemplate
  failurePolicy: Fail
  name: muplinktemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinktemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-vxlan
  failurePolicy: Fail
  name: mvxlan-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-vxlantemplate
  failurePolicy: Fail
  name: mvxlantemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlantemplates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-bridge
  failurePolicy: Fail
  name: vbridge-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridges
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-bridgetemplate
  failurePolicy: Fail
  name: vbridgetemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridgetemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-uplink
  failurePolicy: Fail
  name: vuplink-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-uplinktemplate
  failurePolicy: Fail
  name: vuplinktemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinktemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-vxlan
  failurePolicy: Fail
  name: vvxlan-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-vxlantemplate
  failurePolicy: Fail
  name: vvxlantemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlantemplates
  sideEffects: None
