---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-bridge
  failurePolicy: Fail
  name: mbridge.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridges
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-bridgeconfig
  failurePolicy: Fail
  name: mbridgeconfig.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridgeconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-router
  failurePolicy: Fail
  name: mrouter.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-subnet
  failurePolicy: Fail
  name: msubnet.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - subnets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-uplink
  failurePolicy: Fail
  name: muplink.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-uplinkconfig
  failurePolicy: Fail
  name: muplinkconfig.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinkconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-vxlan
  failurePolicy: Fail
  name: mvxlan.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kvnet-kojuro-date-v1alpha1-vxlanconfig
  failurePolicy: Fail
  name: mvxlanconfig.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlanconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-bridge
  failurePolicy: Fail
  name: vbridge.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridges
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-bridgeconfig
  failurePolicy: Fail
  name: vbridgeconfig.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bridgeconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-router
  failurePolicy: Fail
  name: vrouter.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - routers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-subnet
  failurePolicy: Fail
  name: vsubnet.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - subnets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-uplink
  failurePolicy: Fail
  name: vuplink.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-uplinkconfig
  failurePolicy: Fail
  name: vuplinkconfig.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - uplinkconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-vxlan
  failurePolicy: Fail
  name: vvxlan.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlans
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kvnet-kojuro-date-v1alpha1-vxlanconfig
  failurePolicy: Fail
  name: vvxlanconfig.kb.io
  rules:
  - apiGroups:
    - kvnet.kojuro.date
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vxlanconfigs
  sideEffects: None
