---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridgeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridgeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridgeconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridges/finalizers
  verbs:
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - subnets/finalizers
  verbs:
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - subnets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinkconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinkconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinkconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinks/finalizers
  verbs:
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinks/status
  verbs:
  - get
  - patch
  - update
