---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridges
  - bridgetemplates
  - uplinks
  - uplinktemplates
  - vxlans
  - vxlantemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridges/finalizers
  - bridgetemplates/finalizers
  - uplinks/finalizers
  - uplinktemplates/finalizers
  - vxlans/finalizers
  - vxlantemplates/finalizers
  verbs:
  - update
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - bridges/status
  - bridgetemplates/status
  - uplinks/status
  - uplinktemplates/status
  - vxlans/status
  - vxlantemplates/status
  verbs:
  - get
  - patch
  - update
