# permissions for end users to view uplinkconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: uplinkconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kvnet
    app.kubernetes.io/part-of: kvnet
    app.kubernetes.io/managed-by: kustomize
  name: uplinkconfig-viewer-role
rules:
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinkconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kvnet.kojuro.date
  resources:
  - uplinkconfigs/status
  verbs:
  - get
