apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeployment
  labels:
    app: sampledeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledeployment
  template:
    metadata:
      labels:
        app: sampledeployment
      annotations:
        k8s.v1.cni.cncf.io/networks: br0-conf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: bridge.kvnet.kojuro.date/br0
                operator: Exists
      containers:
      - name: samplepod
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: tjjh89017/alpine-nettools:latest
        securityContext:
          privileged: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampledeployment2
  labels:
    app: sampledeployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampledeployment2
  template:
    metadata:
      labels:
        app: sampledeployment2
      annotations:
        k8s.v1.cni.cncf.io/networks: br1-conf
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: bridge.kvnet.kojuro.date/br1
                operator: Exists
      containers:
      - name: samplepod
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: tjjh89017/alpine-nettools:latest
        securityContext:
          privileged: true
