## Append samples you want in your CSV to this file as resources ##
resources:
- kvnet_v1alpha1_bridgeconfig.yaml
- kvnet_v1alpha1_bridge.yaml
- kvnet_v1alpha1_uplinkconfig.yaml
- kvnet_v1alpha1_uplink.yaml
- k8s.cni.cncf.io_v1_networkattachmentdefinition.yaml
- kvnet_v1alpha1_subnet.yaml
- kvnet_v1alpha1_router.yaml
- kvnet_v1alpha1_vxlan.yaml
- kvnet_v1alpha1_vxlanconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
