apiVersion: kvnet.kojuro.date/v1alpha1
kind: VXLAN
metadata:
  labels:
    app.kubernetes.io/name: kvnet
    app.kubernetes.io/managed-by: kustomize
  name: vxlan-sample
spec:
  # TODO(user): Add fields here
