apiVersion: kvnet.kojuro.date/v1alpha1
kind: UplinkConfig
metadata:
  labels:
    app.kubernetes.io/name: uplinkconfig
    app.kubernetes.io/instance: uplinkconfig-sample
    app.kubernetes.io/part-of: kvnet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kvnet
  name: uplinkconfig-sample
spec:
  selector: {}
  bond: bond0 
  template:
    spec:
      mode: "active-backup"
      slaves:
      - nic0
      - nic1
      master: br0

  # TODO(user): Add fields here
