apiVersion: kvnet.kojuro.date/v1alpha1
kind: Uplink
metadata:
  labels:
    app.kubernetes.io/name: uplink
    app.kubernetes.io/instance: uplink-sample
    app.kubernetes.io/part-of: kvnet
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kvnet
  name: uplink-sample
spec:
  # TODO(user): Add fields here
