apiVersion: kvnet.kojuro.date/v1alpha1
kind: VXLANTemplate
metadata:
  name: vxlan0
spec:
  vxlanName: vxlan0
  vxlanID: 100
  nodeSelector:
    matchLabels:
      kvnet.kojuro.date/role: worker
  template:
    spec:
      master: br0
      dev: eth0
      external: true
      vniFilter: true
      learning: false
      bridgeLearning: false
